### ISSUE TITLE
Does not build on python 3.11

### ISSUE THREAD

**Issue by JC3** [tizilogic/PyFastNoiseLite#1]
```
  × Building wheel for pyfastnoiselite (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-arm64-cpython-311
      creating build/lib.macosx-13-arm64-cpython-311/pyfastnoiselite
      copying src/pyfastnoiselite/__init__.py -> build/lib.macosx-13-arm64-cpython-311/pyfastnoiselite
      running build_ext
      building 'pyfastnoiselite.pyfastnoiselite' extension
      creating build/temp.macosx-13-arm64-cpython-311
      creating build/temp.macosx-13-arm64-cpython-311/src
      creating build/temp.macosx-13-arm64-cpython-311/src/pyfastnoiselite
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -Iext/FastNoise -Iext/CPPWrapper -I/Users/cipriani_pro2023/pyenv-zed/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/pyfastnoiselite/pyfastnoiselite.cpp -o build/temp.macosx-13-arm64-cpython-311/src/pyfastnoiselite/pyfastnoiselite.o -std=c++11 -stdlib=libc++
      src/pyfastnoiselite/pyfastnoiselite.cpp:220:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```
Apparently *longintrepr.h* was moved to a subfolder in 3.11: https://github.com/cython/cython/issues/4461

**Comment by tcdude** [comment]
Should be fixed with the latest commit I pushed. 

Thank you

**Comment by JC3** [comment]
@tcdude Sweet, thanks. Any chance you could push the latest version to PyPI? :)

**Comment by tcdude** [comment]
I tried to adapt my outdated CI workflow to something more modern.. Doesn't like to play well with PyPy and I also skip 32bit binaries (because it's 2023..), but a new release should be up after the current run finishes..

So if you're using a 32 bit system or PyPy, no binaries for you! (or feel free to debug and fix the `cibuildwheel` workflow for those and make a PR, otherwise)
